project                 = "my-user-project-326713"
network_name            = "vpc-network-dev"
network                 = "default"
subnetwork              = "prod"
subnetwork_project      = "vc-dev-1"
auto_create_subnetworks = true
vm_name                 = "jenkins-dev-server"
machine_type            = "e2-medium"
zone                    = "us-central1-c"
tags                    = ["allow-elastic"]
image                   = "cos-cloud/cos-stable" 
#labels                 =  ["function","log-server" ]
size                    = "10"
type                    = "pd-standard"
firewall_name           = "elastic-dev"
ports                   = [ "22", "80", "8080" ]
protocol                = "tcp"
source_ranges           = [ "10.0.0.0/8" ]
target_tags                    = ["allow-elastic"]
