network_name                        = "vpc-network-dev"
network                             = "default"
#subnetwork                         = "prod"
#subnetwork_project                 = "My user project" 
auto_create_subnetworks             = true
machine_type                        = "e2-medium"
zone                                = "us-central1-c"
region                              = "us-central1"
tags                                = [ "allow-jenkins" ]
image                               = "centos-cloud/centos-7"
cluster_name                        =
cluster_service_account_name        =
cluster_service_account_description = 
master_ipv4_cidr_block              =
vpc_cidr_block                      =
vpc_secondary_cidr_block            = 
