network_name            = "vpc-network-dev"
network                 = "default"
#subnetwork             = "prod"
#subnetwork_project     = "My user project" 
auto_create_subnetworks = true
vm_name                 = "jenkins-dev-server"
machine_type            = "e2-medium"
zone                    = "us-central1-c"
region                  = "us-central1"
tags                    = [ "allow-jenkins" ]
image                   = "centos-cloud/centos-7"
